[package]
name = "rust-collections"
version = "0.1.0"
edition = "2021"

[dependencies]
cache-size = { version = "0.5.0" }

[dev-dependencies]
criterion = "0.3"
min-max-heap = "1.3.0"
rand = "0.8.5"

[[bench]]
name = "main_bench"
harness = false
